Add encrypt file processes

diff --git a/processes b/processes
--- a/processes
+++ b/processes
@@ -7,6 +7,8 @@ source "$(_decompose-project-root)"/.decompose/environment/lib/common/processes
 # Declare processes
 # shellcheck disable=SC2034
 DECOMPOSE_PROCESSES=( 'ansible' 'run-playbook' 'encrypt-string' 'decrypt-string'
+  'create-encrypted-file' 'edit-encrypted-file' 'decrypt-file'
+  'view-encrypted-file' 'encrypt-file'
   "${DECOMPOSE_COMMON_PROCESSES[@]}" )
 
 _decompose-process-run-playbook() {
@@ -118,5 +120,99 @@ _decompose-process-decrypt-string_help() {
   echo "  Decrypt a string for used in variable file"
   echo "    EX: 'decompose decrypt-string'"
 }
+
+_decompose-process-ansible-vault-file() {
+  local c; c="$1"
+  if [ -z "$c" ]; then
+    echo "Missing command for ansible-vault"
+    return 1
+  fi
+
+  local f; f="$2"
+	if [ -z "$f" ]; then
+    echo "Please specify a file to create for the first parameter."
+    return 1
+  fi
+
+  local additional_params; additional_params=(${*:3})
+
+  case "$c" in
+    "create" | "edit" | "encrypt" | "decrypt" | "view")
+      ansible-vault --vault-password-file="$VAULT_PASS_FILE" "$c" "$f" "${additional_params[@]}"
+      ;;
+    *)
+      echo "$c is not a valid command"
+      return 1
+      ;;
+  esac
+}
+
+_decompose-process-create-encrypted-file() {
+  if ! _decompose-process-ansible-vault-file create "$@"
+  then
+    _decompose-process-create-encrypted-file_help
+  fi
+}
+_decompose-process-create-encrypted-file_help() {
+  echo "  Create encrypt variable file"
+  echo "    Param 1: File path"
+  echo "    Param 2+: passed to 'ansible-vault' command"
+}
+_decompose-process-edit-encrypted-file() {
+  if ! _decompose-process-ansible-vault-file edit "$@"
+  then
+    _decompose-process-edit-encrypted-file_help
+  fi
+}
+_decompose-process-edit-encrypted-file_help() {
+  echo "  Edit encrypted file"
+  echo "    Param 1: File path"
+  echo "    Param 2+: passed to 'ansible-vault' command"
+}
+_decompose-process-encrypt-file() {
+  if ! _decompose-process-ansible-vault-file encrypt "$@"
+  then
+    _decompose-process-encrypt-encrypted-file_help
+  fi
+}
+_decompose-process-encrypt-file_help() {
+  echo "  Encrypt unencrypted file"
+  echo "    Param 1: File path"
+  echo "    Param 2+: passed to 'ansible-vault' command"
+}
+_decompose-process-decrypt-file() {
+  if ! _decompose-process-ansible-vault-file decrypt "$@"
+  then
+    _decompose-process-decrypt-file_help
+  fi
+}
+_decompose-process-decrypt-file_help() {
+  echo "  Decrypt encrypted file"
+  echo "    Param 1: File path"
+  echo "    Param 2+: passed to 'ansible-vault' command"
+}
+_decompose-process-view-encrypted-file() {
+  if ! _decompose-process-ansible-vault-file view "$@"
+  then
+    _decompose-process-view-encrypted-file_help
+  fi
+}
+_decompose-process-view-encrypted-file_help() {
+  echo "  View encrypted values in encrypted file"
+  echo "    Param 1: File path"
+  echo "    Param 2+: passed to 'ansible-vault' command"
+}
+
+#_decompose-process-edit-encrypted-file() {
+#  local f; f="$1"
+#	if [ ! -f "$f" ]; then
+#    echo "Please specify a file to create for the first parameter."
+#    _decompose-process-create-encrypted-file_help
+#    exit 1
+#  fi
+#  local additional_params; additional_params=(${*:2})
+#
+#  ansible-vault --vault-password-file="$VAULT_PASS_FILE" create "$f" "${additional_params[@]}"
+#}
 
 # vim:syntax=sh
